name: Build and Deploy UrlPulse Container App on Azure

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: urlpulse
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  RESOURCE_GROUP: url-pulse-rg
  CONTAINER_APP: urlpulse

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/*.trx'

  docker-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() # ensures job only runs if tests passed

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: >
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Docker login to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login $REGISTRY \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build image
      run: |
        docker build \
          -f Web/Dockerfile \
          -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t $REGISTRY/${{ env.IMAGE_NAME }}:latest \
          .

    - name: Push image
      run: |
        docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest

    - name: Deploy revision
      run: |
        az containerapp update \
          --name $CONTAINER_APP \
          --resource-group $RESOURCE_GROUP \
          --image $REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Show URL
      run: |
        az containerapp show \
          --name $CONTAINER_APP \
          --resource-group $RESOURCE_GROUP \
          --query "properties.configuration.ingress.fqdn" \
          --output tsv